routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\NotificationsController;
use App\Http\Controllers\HelperController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\SiteMapController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\RedirectionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\TrafficsController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\MenuLinkController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\ContactReplyController;
use App\Http\Controllers\AnnouncementController;


Auth::routes();
Route::get('/', function () {return view('front.index');})->name('home');

Route::prefix('admin')->middleware(['auth','ActiveAccount'])->name('admin.')->group(function () {

    Route::get('/',[AdminController::class,'index'])->name('index');

    Route::middleware(['CheckRole:ADMIN'])->group(function () {

        
        Route::resource('announcements',AnnouncementController::class);
        Route::resource('files',FileController::class);
        Route::post('contacts/resolve',[ContactController::class,'resolve'])
                ->can('resolve',\App\Models\Contact::class)->name('contacts.resolve');
        Route::resource('contacts',ContactController::class);
        Route::resource('menus',MenuController::class);
        Route::resource('users',UserController::class);
        Route::resource('articles',ArticleController::class);
        Route::resource('pages',PageController::class);
        Route::resource('contact-replies',ContactReplyController::class);
        Route::post('faqs/order',[FaqController::class,'order'])->name('faqs.order');
        Route::resource('faqs',FaqController::class);
        Route::post('menu-links/get-type',[MenuLinkController::class,'getType'])->name('menu-links.get-type');
        Route::post('menu-links/order',[MenuLinkController::class,'order'])->name('menu-links.order');
        Route::resource('menu-links',MenuLinkController::class);
        Route::resource('categories',CategoryController::class);
        Route::resource('redirections',RedirectionController::class);
        Route::get('traffics',[TrafficsController::class,'index'])->name('traffics.index');
        Route::get('traffics/{traffic}/logs',[TrafficsController::class,'logs'])->name('traffics.logs');
        Route::get('error-reports',[TrafficsController::class,'error_reports'])->name('traffics.error-reports');
        Route::get('error-reports/{report}',[TrafficsController::class,'error_report'])->name('traffics.error-report');
        Route::prefix('settings')->name('settings.')->group(function () {
            Route::get('/',[SettingController::class,'index'])->name('index');
            Route::put('/{settings}/update',[SettingController::class,'update'])->name('update');
        });
    });

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[HelperController::class,'upload_image'])->name('image');
        Route::post('/file',[HelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[HelperController::class,'remove_files'])->name('remove-file');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/',[ProfileController::class,'index'])->name('index')->can('control', User::class);
        Route::get('/edit',[ProfileController::class,'edit'])->name('edit')->can('control', User::class);
        Route::put('/update',[ProfileController::class,'update'])->name('update')->can('control', User::class);
        Route::put('/update-password',[ProfileController::class,'update_password'])->name('update-password')->can('control', User::class);
        Route::put('/update-email',[ProfileController::class,'update_email'])->name('update-email')->can('control', User::class);
    });

    Route::prefix('notifications')->name('notifications.')->group(function () {
        Route::get('/',[NotificationsController::class,'index'])->name('index');
        Route::get('/ajax',[NotificationsController::class,'ajax'])->name('ajax');
        Route::post('/see',[NotificationsController::class,'see'])->name('see');
        Route::get('/create',[NotificationsController::class,'create'])->name('create');
        Route::post('/create',[NotificationsController::class,'store'])->name('store');
    });
    
});


Route::get('blocked',[HelperController::class,'blocked_user'])->name('blocked');
Route::get('robots.txt',[HelperController::class,'robots']);
Route::get('manifest.json',[HelperController::class,'manifest'])->name('manifest');
Route::get('sitemap.xml',[SiteMapController::class,'sitemap']);
Route::get('sitemaps/links','SiteMapController@custom_links');
Route::get('sitemaps/{name}/{page}/sitemap.xml',[SiteMapController::class,'viewer']);


Route::view('contact','front.pages.contact')->name('contact');
Route::get('page/{page}',[FrontController::class,'page'])->name('page.show');
Route::get('category/{category}',[FrontController::class,'category'])->name('category.show');
Route::get('article/{article}',[FrontController::class,'article'])->name('article.show');
Route::get('blog',[FrontController::class,'blog'])->name('blog');
Route::post('contact',[FrontController::class,'contact_post'])->name('contact-post');

app/Http/Controllers/NotificationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\View\Components\Notifications as NotificationComponent;
class NotificationsController extends Controller
{
    public function index(Request $request){
        $user=auth()->user();
        if($request->user_id!=null)
            $user=\App\Models\User::where('id',$request->user_id)->firstOrFail();
        if(auth()->user()->id==$user->id)
            $user->unreadNotifications->markAsRead();
        $notifications = $user->notifications()->simplePaginate(); 
        return view('admin.notifications.index',compact('notifications'));
    }
    public function see(Request $request){
        session(['seen_notifications'=>0]);
        auth()->user()->unreadNotifications->markAsRead();
    }

    public function ajax(Request $request){

        $notifications = \Auth::user()->notifications()->limit(15)->get(); 
        $not_response  = array(
            'response'                   => (new NotificationComponent($notifications))->render(1),
            'count_unseen_notifications' => intval($notifications->whereNull('read_at')->count()),
        );
        $data = [
            'notifications' => [
                'response'        => $not_response,
                'counter_session' => intval(session('seen_notifications')),
            ],
            'alert' => false,
        ];

        if ($data['notifications']['counter_session'] < $not_response['count_unseen_notifications'])
            $data['alert'] = true; 
  
            session(['seen_notifications' => $not_response['count_unseen_notifications']]);
        return $data;
    }

    public function create(Request $request){
        $request->validate(['user_id'=>"required|exists:users,id"]);
        return view('admin.notifications.create');
    }
    public function store(Request $request){

        $contact = \App\Models\Contact::create([
            'user_id'=>$request->user_id,
            'message'=>$request->content,
            'has_support_reply'=>1,
            'status'=>"DONE",
        ]);
        if($request->hasFile('files'))
        foreach($request['files'] as $file){
            $uploaded_file = $this->store_file([
                'source'=>$file,
                'validation'=>"file",
                'path_to_save'=>'/uploads/contacts/',
                'type'=>'CONTACT', 
                'user_id'=>auth()->user()->id,
                'resize'=>[500,1000],
                'small_path'=>'small/',
                'visibility'=>'PUBLIC',
                'file_system_type'=>env('FILESYSTEM_DRIVER'),
                /*'watermark'=>true,*/
                'compress'=>'auto'
            ]);
            $this->use_hub_file($uploaded_file['filename'],$contact->id,$request->user_id);
        } 

        $user = \App\Models\User::where('id',$request->user_id)->firstOrFail();
        (new \MainHelper)->notify_user([
            'user_id'=>$request->user_id,
            'content'=>[$request->content],
            'btn_text'=>"عرض التنبيه",
            'action_url'=>route('admin.contacts.show',$contact)
        ]);
        toastr()->success('تم إرسال التنبيه بنجاح');
        return redirect()->route('admin.notifications.index',['user_id'=>$request->user_id]);

    }

}

app/View/Components/Notifications.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Notifications extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public $notifications;
    public function __construct($notifications)
    {
        $this->notifications=$notifications;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render($render=null)
    {
        $notifications=$this->notifications; 
            return (null!==$render)?view('components.notifications',compact('notifications'))->render():view('components.notifications'); 
    }
}


  

resources/views/admin/notifications/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 p-3">
    <div class="col-12 col-lg-12 p-0 ">
        <form id="validate-form" class="row" enctype="multipart/form-data" method="POST" action="{{route('admin.notifications.store')}}">
            @csrf
            <input type="hidden" name="user_id" value="{{request()->get('user_id')}}">
            <div class="col-12 col-lg-4 p-0 main-box">
                <div class="col-12 px-0">
                    <div class="col-12 px-3 py-3">
                        <span class="fas fa-info-circle"></span> إرسال إشعار
                    </div>
                    <div class="col-12 divider" style="min-height: 2px;"></div>
                </div>
                <div class="col-12 p-3 row">
             
                    <div class="col-12 col-lg-12 p-2">
                        <div class="col-12">
                            محتوى الإشعار
                        </div>
                        <div class="col-12 pt-3">
                            <textarea name="content" class="form-control" style="min-height:150px" required>{{old('content',$notification??"")}}</textarea>
                        </div>
                    </div>
                    <div class="col-12 p-2">
                        <div class="col-12">
                            مرفقات
                        </div>
                        <div class="col-12 pt-3">
                            <input type="file" name="files[]" multiple class="form-control">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 p-3">
                <button class="btn btn-success" id="submitEvaluation">حفظ</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/notifications/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container d-flex justify-content-end">
	@if(request()->get('user_id')!=null)
	@can('create-notifications')
	<a href="{{route('admin.notifications.create',['user_id'=>request()->get('user_id')])}}">
		<span class="btn btn-primary"><span class="fas fa-bells"></span> إرسال تنبيه</span>
	</a>
	@endcan
	@endif
</div>
<div class="col-12 container">
	<div class="col-12 p-3 notifications-container" >
		<x-notifications :notifications="$notifications" />
	</div>
	<div class="col-12 p-3">
		{{$notifications->links()}}
	</div>
</div>
@endsection