routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\NotificationsController;
use App\Http\Controllers\HelperController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\SiteMapController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\RedirectionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\TrafficsController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\MenuLinkController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\ContactReplyController;
use App\Http\Controllers\AnnouncementController;


Auth::routes();
Route::get('/', function () {return view('front.index');})->name('home');

Route::prefix('admin')->middleware(['auth','ActiveAccount'])->name('admin.')->group(function () {

    Route::get('/',[AdminController::class,'index'])->name('index');

    Route::middleware(['CheckRole:ADMIN'])->group(function () {

        
        Route::resource('announcements',AnnouncementController::class);
        Route::resource('files',FileController::class);
        Route::post('contacts/resolve',[ContactController::class,'resolve'])
                ->can('resolve',\App\Models\Contact::class)->name('contacts.resolve');
        Route::resource('contacts',ContactController::class);
        Route::resource('menus',MenuController::class);
        Route::resource('users',UserController::class);
        Route::resource('articles',ArticleController::class);
        Route::resource('pages',PageController::class);
        Route::resource('contact-replies',ContactReplyController::class);
        Route::post('faqs/order',[FaqController::class,'order'])->name('faqs.order');
        Route::resource('faqs',FaqController::class);
        Route::post('menu-links/get-type',[MenuLinkController::class,'getType'])->name('menu-links.get-type');
        Route::post('menu-links/order',[MenuLinkController::class,'order'])->name('menu-links.order');
        Route::resource('menu-links',MenuLinkController::class);
        Route::resource('categories',CategoryController::class);
        Route::resource('redirections',RedirectionController::class);
        Route::get('traffics',[TrafficsController::class,'index'])->name('traffics.index');
        Route::get('traffics/{traffic}/logs',[TrafficsController::class,'logs'])->name('traffics.logs');
        Route::get('error-reports',[TrafficsController::class,'error_reports'])->name('traffics.error-reports');
        Route::get('error-reports/{report}',[TrafficsController::class,'error_report'])->name('traffics.error-report');
        Route::prefix('settings')->name('settings.')->group(function () {
            Route::get('/',[SettingController::class,'index'])->name('index');
            Route::put('/{settings}/update',[SettingController::class,'update'])->name('update');
        });
    });

    Route::prefix('upload')->name('upload.')->group(function(){
        Route::post('/image',[HelperController::class,'upload_image'])->name('image');
        Route::post('/file',[HelperController::class,'upload_file'])->name('file');
        Route::post('/remove-file',[HelperController::class,'remove_files'])->name('remove-file');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/',[ProfileController::class,'index'])->name('index')->can('control', User::class);
        Route::get('/edit',[ProfileController::class,'edit'])->name('edit')->can('control', User::class);
        Route::put('/update',[ProfileController::class,'update'])->name('update')->can('control', User::class);
        Route::put('/update-password',[ProfileController::class,'update_password'])->name('update-password')->can('control', User::class);
        Route::put('/update-email',[ProfileController::class,'update_email'])->name('update-email')->can('control', User::class);
    });

    Route::prefix('notifications')->name('notifications.')->group(function () {
        Route::get('/',[NotificationsController::class,'index'])->name('index');
        Route::get('/ajax',[NotificationsController::class,'ajax'])->name('ajax');
        Route::post('/see',[NotificationsController::class,'see'])->name('see');
        Route::get('/create',[NotificationsController::class,'create'])->name('create');
        Route::post('/create',[NotificationsController::class,'store'])->name('store');
    });
    
});


Route::get('blocked',[HelperController::class,'blocked_user'])->name('blocked');
Route::get('robots.txt',[HelperController::class,'robots']);
Route::get('manifest.json',[HelperController::class,'manifest'])->name('manifest');
Route::get('sitemap.xml',[SiteMapController::class,'sitemap']);
Route::get('sitemaps/links','SiteMapController@custom_links');
Route::get('sitemaps/{name}/{page}/sitemap.xml',[SiteMapController::class,'viewer']);


Route::view('contact','front.pages.contact')->name('contact');
Route::get('page/{page}',[FrontController::class,'page'])->name('page.show');
Route::get('category/{category}',[FrontController::class,'category'])->name('category.show');
Route::get('article/{article}',[FrontController::class,'article'])->name('article.show');
Route::get('blog',[FrontController::class,'blog'])->name('blog');
Route::post('contact',[FrontController::class,'contact_post'])->name('contact-post');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
    public $guarded=['id','created_at','updated_at'];
    public function user(){
        return $this->belongsTo(\App\Models\User::class);
    }
    public function replies()
    {
        return $this->hasMany(\App\Models\ContactReply::class)/*->orderBy('id','DESC')*/;
    }
    public function files(){
        return $this->hasMany(\App\Models\HubFile::class,'type_id')->where('type','CONTACT');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{


    public function __construct()
    {
        $this->authorizeResource(Contact::class, 'contact'); 
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $contacts =  Contact::where(function($q)use($request){
            if($request->id!=null)
                $q->where('id',$request->id);
            if($request->user_id!=null)
                $q->where('user_id',$request->user_id);
            if($request->q!=null)
                $q->where('name','LIKE','%'.$request->q.'%')->orWhere('phone','LIKE','%'.$request->q.'%')->orWhere('email','LIKE','%'.$request->q.'%')->orWhere('message','LIKE','%'.$request->q.'%');
        })->orderBy('id','DESC')->paginate();

        return view('admin.contacts.index',compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        return view('admin.contacts.show',compact('contact'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        toastr()->success('تم حذف طلب التواصل بنجاح','عملية ناجحة');
        return redirect()->route('admin.contacts.index');
    }

    public function resolve(Request $request){
        $contact = \App\Models\Contact::where('id',$request->id)->firstOrFail();
        $contact->update(['status'=>$contact->status=="PENDING"?"DONE":"PENDING"]);
        return ['status'=>$contact->status=="DONE"?"DONE":"PENDING" ];
    }
}

resources/views/admin/contacts/index.blade.php
@extends('layouts.admin')
@section('content')
<style type="text/css">
	.ticket-resolved{
		background: #effff0!important;
	}
</style>
<div class="col-12 p-3">
	<div class="col-12 col-lg-12 p-0 main-box">
	 
		<div class="col-12 px-0">
			<div class="col-12 p-0 row">
				<div class="col-12 col-lg-4 py-3 px-3">
					<span class="fas fa-contacts"></span> الاتصالات
				</div>
				<div class="col-12 col-lg-4 p-2">
				</div>
			</div>
			<div class="col-12 divider" style="min-height: 2px;"></div>
		</div>

		<div class="col-12 py-2 px-2 row">
			<div class="col-12 col-lg-4 p-2">
				<form method="GET">
					<input type="text" name="q" class="form-control" placeholder="بحث ... " value="{{request()->get('q')}}">
				</form>
			</div>
		</div>
		<div class="col-12 p-3" style="overflow:auto">
			<div class="col-12 p-0" style="min-width:1100px;">
				
			
			<table class="table table-bordered  table-hover">
				<thead>
					<tr>
						<th>#</th>
						@can('resolve',\App\Models\Contact::class)
						<th scope="col" style="width:40px;">تم</th>
						@endcan
						<th>المستخدم</th>
						<th>محتوى التذكرة</th>
						<th>تحكم</th>
					</tr>
				</thead>  
				<tbody>
					@foreach($contacts as $contact)
					<tr 
					id="ticket_{{$contact->id}}"
					class="@if($contact->status=="DONE") ticket-resolved @endif" 
					 >
						<td>{{$contact->id}}</td>
						@can('resolve',\App\Models\Contact::class)
						<td scope="col" style="width:30px;">
		      
					      	<div class="form-switch">
							  <input class="form-check-input toggle-contact-resolving" type="checkbox" id="flexSwitchCheckDefault" style="width:40px;height: 21px;" {{$contact->status=="DONE"?"checked":""}} data-id="{{$contact->id}}">
							</div>
						 
					      </td>
					     @endcan
						<td>

							@if($contact->user_id!=null)

	                        	<a href="{{route('admin.users.show',$contact->user)}}" class="d-inline-block text-center">
	                                <img src="{{$contact->user->getUserAvatar()}}" style="width: 45px;height: 45px;display: inline-block;border-radius: 50%!important;padding: 3px;" class="mx-auto" alt="صورة المستخدم">
	                                <span style="display: inline-block;position: relative;top: 6px; " class="px-2 pt-0  text-start kufi">{{$contact->user->name}}</span>
	                            </a> 
	                            @else
	                            
	                                <img src="https://manager.almadarisp.com/user/img/user.png" style="width: 45px;height: 45px;display: inline-block;border-radius: 50%!important;padding: 3px;" class="mx-auto" alt="صورة المستخدم">
	                                <span style="display: inline-block;position: relative;top: 6px; " class="px-2 pt-0  text-start kufi">{{$contact->name}}<br>{{$contact->email}}<br>{{$contact->phone}}</span>

	                   
	                            @endif
						</td>
						<td>{{mb_strimwidth($contact->message,0,80,'...')}}
							<br>
							آخر رد من :
							@php
							$last_reply= $contact->replies()->orderBy('id','DESC')->first();
							@endphp
							@if($last_reply!=null)
								{{
									$last_reply->is_support_reply==1?"الدعم الفني":$contact->name
								}}
								<br>
								{{
									mb_strimwidth($last_reply->content,0,80,'...') 
								}}
							@else
							{{$contact->name}}
							@endif
							  
						</td>
					 
						<td style="width: 180px;">
							@can('view',$contact)
							<a href="{{route('admin.contacts.show',$contact)}}">
							<span class="btn  btn-success btn-sm font-1 mx-1">
								<span class="fal fa-paper-plane"></span> مراسلة
							</span>
							</a>
							@endcan
							@can('delete',$contact)
							<form method="POST" action="{{route('admin.contacts.destroy',$contact)}}" class="d-inline-block">@csrf @method("DELETE")
								<button class="btn  btn-outline-danger btn-sm font-1 mx-1" onclick="var result = confirm('هل أنت متأكد من عملية الحذف ؟');if(result){}else{event.preventDefault()}">
									<span class="fas fa-trash "></span> حذف
								</button>
							</form>
							@endif
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			</div>
		</div>
		<div class="col-12 p-3">
			{{$contacts->appends(request()->query())->render()}}
		</div>
	</div>
</div>
@endsection
@section('scripts')
@can('resolve',\App\Models\Contact::class))
<script type="text/javascript">
	$('.toggle-contact-resolving').on('change',function(){
		var id =$(this).attr('data-id');
		$.ajax({
		  method: "POST",
		  url: "{{route('admin.contacts.resolve')}}",
		  data: { _token: "{{csrf_token()}}", id: id }
		}).done(function(res){
			if(res.status=="DONE"){ 
				$('#ticket_'+id).addClass('ticket-resolved');
			}
			else{
				$('#ticket_'+id).removeClass('ticket-resolved');
			}
		});
	});
</script>
@endcan
@endsection

resources/views/admin/contacts/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-12 py-0 px-3 row">
    <div class="col-12  pt-4" style="background: #fff;min-height: 80vh">
        <div class="col-12 px-3">
            <h5>عرض الرسالة رقم {{$contact->id}} القادمة من {{$contact->name}}</h5>
        </div>
        @if($contact->files()->count() !=0)
        <div class="col-12 px-3">
        	<h6>مرفقات</h6>
        	@include('admin.templates.attachments',['attachments'=>$contact->files])
        </div>
        @endif
        <div class="col-12  px-3 py-1 mt-4">

        	<div class="col-12  " style="direction: rtl" id="{{$contact->id}}">
	                <div class="col-12 col-md-10 col-lg-9 col-xl-6 p-2 row rounded-2" style="direction: rtl;background: #f1f1f1;">
	                    <div style="width:70px;" class="text-center d-none d-md-flex align-items-start">
	                        <div class="d-inline-block">

	                        	@if($contact->user_id!=null)

	                        	<a href="{{route('admin.users.index',['id'=>$contact->user_id])}}" class="d-inline-block text-center">
	                                <img src="{{$contact->user->getUserAvatar()}}" style="width: 45px;height: 45px;display: inline-block;border-radius: 50%!important;padding: 3px;" class="mx-auto" alt="صورة المستخدم">
	                                <span style="display: inline-block;position: relative;top: 6px; " class="px-2 pt-0  float-end kufi"> </span>
	                            </a>

	                            
	                            @else
	                            

	                        
	                                <img src="https://manager.almadarisp.com/user/img/user.png" style="width: 45px;height: 45px;display: inline-block;border-radius: 50%!important;padding: 3px;" class="mx-auto" alt="صورة المستخدم">
	                                <span style="display: inline-block;position: relative;top: 6px; " class="px-2 pt-0  float-end kufi"> </span>
	                            

	                            @endif
	                        </div>
	                    </div>
	                    <div class=" px-2" style="width: calc(100% - 70px);">
	                        <div class="col-12 rounded py-2" style="background: var(--message-sender-bg);">
	                            <div class="col-12 px-0 row">
	                                	<div class="col-7 px-0">

	                                		@if($contact->user_id!=null)
	                                    <a href="{{route('admin.users.index',['id'=>$contact->user_id])}}" class="d-inline-block text-center">
	                                        
	                                        <span style="font-size:13px;opacity: .7;font-weight: bold;color: var(--bg-color-0)" class="kufi">{{$contact->user->name}}</span>
	                                    </a>

	                                         
	                                         @else

	                             
	                                        
	                                        <span style="font-size:13px;opacity: .7;font-weight: bold;color: var(--bg-color-0)" class="kufi">{{$contact->name }}<br>{{ $contact->email}} <br>{{$contact->phone}}</span>
	                                     

	                                         @endif

	                                         </div>
	                                <div class="col-5 px-0 text-end">
	                                    <span style="font-size:14px;opacity: .7" class="naskh">{{\Carbon::parse($contact->created_at)->diffForHumans()}}</span>
	                                </div>
	                            </div>
	                            <div class="col-12 px-0">
	                                <div style=" position: relative;top: 0px;" class="py-2">
	                                    <span style=" position: relative;color: var(--bg-color-0); font-size: 17px;white-space: pre-line;word-wrap: break-word;overflow: hidden;  " class="p-0 naskh"> {{$contact->message}}</span>
	                                </div>
	                                <div class="col-12 px-1">
	                                    <div class="col-12 px-0">
	                                    </div>
	                                </div>
	                            </div> 
	                        </div>
	                    </div>
	                </div>
	            </div> 
        </div>
        <div class="col-12 p-0">


         
        	@foreach($contact->replies as $reply)
	            <div class="col-12 px-1 px-lg-3 row py-2 message" style="direction: rtl;" id="{{$reply->id}}">
	                <div class="col-12 col-md-10 col-lg-9 col-xl-6 p-2 row rounded-2" style="direction: rtl;background:#d7eeff;">
	                    <div style="width:70px;" class="text-center d-none d-md-flex align-items-start">
	                        <div class="d-inline-block">
	                            <a href="{{route('admin.users.index',['id'=>$reply->user_id])}}" class="d-inline-block text-center">
	                                <img src="{{$reply->user->getUserAvatar()}}" style="width: 45px;height: 45px;display: inline-block;border-radius: 50%!important;padding: 3px;" class="mx-auto" alt="صورة المستخدم">
	                                <span style="display: inline-block;position: relative;top: 6px; " class="px-2 pt-0  float-end kufi"> </span>
	                            </a>
	                        </div>
	                    </div>
	                    <div class=" px-2" style="width: calc(100% - 70px);">
	                        <div class="col-12 rounded py-2" style="background: var(--message-sender-bg);">
	                            <div class="col-12 px-0 row">
	                                <div class="col-7 px-0">
	                                    <a href="{{route('admin.users.index',['id'=>$reply->user_id])}}" class="d-inline-block text-center">
	                                        
	                                        <span style="font-size:13px;opacity: .7;font-weight: bold;color: var(--bg-color-0)" class="kufi">{{$reply->user->name}}</span></a>

	                                         </div>
	                                <div class="col-5 px-0 text-end">
	                                    <span style="font-size:14px;opacity: .7" class="naskh">{{\Carbon::parse($reply->created_at)->diffForHumans()}}</span>
	                                </div>
	                            </div>
	                            <div class="col-12 px-0">
	                                <div style=" position: relative;top: 0px;" class="py-2">
	                                    <span style=" position: relative;color: var(--bg-color-0); font-size: 17px;white-space: pre-line;word-wrap: break-word;overflow: hidden;  " class="p-0 naskh"> {{$reply->content}}</span>
	                                </div>
	                                <div class="col-12 px-1">
	                                    <div class="col-12 px-0">
	                                    </div>
	                                </div>
	                            </div> 
	                        </div>
	                    </div>
	                    @if($reply->files()->count() !=0)
				        <div class="col-12 px-3">
				        	<h6>مرفقات</h6>
				        	@include('admin.templates.attachments',['attachments'=>$reply->files])
				        </div>
				        @endif
	                </div>
	            </div>
            @endforeach


        </div>
        <div class="col-12  px-3 py-1 mt-4">
            <form method="POST" action="{{route('admin.contact-replies.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="col-12 col-md-10 col-lg-9 col-xl-6 p-0 mb-3">
                    <div class="col-12 px-0 pt-1 mb-3">
                        إرسال رد
                    </div>
                    <div class="col-12 px-0">
                        <input type="hidden" name="contact_id" value="{{$contact->id}}">
                        <textarea name="content" class="form-control" min="3" max="1000" style="min-height: 200px"></textarea>
                        <h6>مرفقات</h6>
                        <input type="file" name="files[]" multiple class="form-control col-12 col-lg-6">
                    </div>
                </div>
                <div class="col-12 p-0">
                    <button class="btn btn-primary">إرسال رد</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection